# Generated by Django 4.0.4 on 2022-04-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='用户名', max_length=100, unique=True)),
                ('phone', models.CharField(default='', help_text='手机号', max_length=100, unique=True)),
                ('super_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start_app.user')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
