# Generated by Django 4.0.4 on 2022-04-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_alter_user_options_alter_user_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='super_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='start_app.user'),
        ),
    ]
