# Generated by Django 4.0.4 on 2022-04-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0003_alter_user_super_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户列表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', help_text='用户', max_length=100, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', help_text='手机号', max_length=100, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='super_user',
            field=models.ForeignKey(blank=True, default=None, help_text='上级用户', null=True, on_delete=django.db.models.deletion.PROTECT, to='start_app.user', verbose_name='上级用户'),
        ),
        migrations.CreateModel(
            name='Mechine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(default='', help_text='用户名', max_length=100, unique=True, verbose_name='用户名')),
                ('v', models.IntegerField(default=0, help_text='当前得分', unique=True, verbose_name='当前得分')),
                ('p_now', models.IntegerField(default=0, help_text='当前得分', unique=True, verbose_name='当前得分')),
                ('p_init', models.IntegerField(default=0, help_text='初始得分', unique=True, verbose_name='初始得分')),
                ('history_amount', models.IntegerField(default=0, help_text='历史总产量', unique=True, verbose_name='历史总产量')),
                ('stake_amount', models.IntegerField(default=0, help_text='质押金额', unique=True, verbose_name='质押金额')),
                ('status_now', models.IntegerField(default=0, help_text='当前状态', unique=True, verbose_name='当前状态')),
                ('update_time', models.CharField(default='', help_text='更新时间', max_length=100, unique=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='拥有者', null=True, on_delete=django.db.models.deletion.PROTECT, to='start_app.user', verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '机器列表',
                'db_table': 'mechine',
            },
        ),
    ]
