# Generated by Django 4.0.4 on 2022-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0004_alter_user_options_alter_user_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechine',
            name='owner',
        ),
        migrations.AddField(
            model_name='mechine',
            name='ve',
            field=models.IntegerField(default=0, help_text='ve', verbose_name='ve'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='history_amount',
            field=models.IntegerField(default=0, help_text='历史总产量', verbose_name='历史总产量'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='p_init',
            field=models.IntegerField(default=0, help_text='初始得分', verbose_name='初始得分'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='p_now',
            field=models.IntegerField(default=0, help_text='当前得分', verbose_name='当前得分'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='pubkey',
            field=models.CharField(default='', help_text='矿机公钥', max_length=100, unique=True, verbose_name='矿机公钥'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='stake_amount',
            field=models.IntegerField(default=0, help_text='质押金额', verbose_name='质押金额'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='status_now',
            field=models.IntegerField(default=0, help_text='当前状态', verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='update_time',
            field=models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='v',
            field=models.IntegerField(default=0, help_text='v', verbose_name='v'),
        ),
    ]
