# Generated by Django 4.0.4 on 2022-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0005_remove_mechine_owner_mechine_ve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField(default=0, help_text='pid', verbose_name='pid')),
                ('addr', models.CharField(default='', help_text='addr', max_length=100, verbose_name='addr')),
                ('locked', models.BigIntegerField(default=0, help_text='locked', verbose_name='locked')),
                ('shares', models.BigIntegerField(default=0, help_text='shares', verbose_name='shares')),
                ('availableRewards', models.BigIntegerField(default=0, help_text='availableRewards', verbose_name='availableRewards')),
                ('rewardDebt', models.BigIntegerField(default=0, help_text='rewardDebt', verbose_name='rewardDebt')),
            ],
            options={
                'verbose_name': '质押列表',
                'db_table': 'staker',
            },
        ),
    ]
