# Generated by Django 4.0.4 on 2022-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0006_staker'),
    ]

    operations = [
        migrations.AddField(
            model_name='staker',
            name='update_time',
            field=models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间'),
        ),
    ]
