# Generated by Django 4.0.4 on 2022-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0007_staker_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMachinCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', help_text='记录时间', max_length=100, verbose_name='记录时间')),
                ('data', models.BigIntegerField(default=0, help_text='data', verbose_name='data')),
                ('update_time', models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '质押列表',
                'db_table': 'daily_machine_count',
            },
        ),
        migrations.CreateModel(
            name='DailyStakeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', help_text='记录时间', max_length=100, verbose_name='记录时间')),
                ('data', models.BigIntegerField(default=0, help_text='data', verbose_name='data')),
                ('update_time', models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '质押列表',
                'db_table': 'daily_stake_amount',
            },
        ),
        migrations.CreateModel(
            name='DailyUserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', help_text='记录时间', max_length=100, verbose_name='记录时间')),
                ('data', models.BigIntegerField(default=0, help_text='data', verbose_name='data')),
                ('update_time', models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '质押列表',
                'db_table': 'daily_user_count',
            },
        ),
    ]
