# Generated by Django 4.0.4 on 2022-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0009_dailymeachine_alter_mechine_history_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField(default=0, help_text='pid', verbose_name='pid')),
                ('owner', models.CharField(default='', help_text='拥有者', max_length=100, unique=True, verbose_name='拥有者')),
                ('commission', models.BigIntegerField(default=0, help_text='佣金', verbose_name='佣金')),
                ('cap', models.BigIntegerField(default=0, help_text='池子容量', verbose_name='池子容量')),
                ('total_stake', models.BigIntegerField(default=0, help_text='total_stake', verbose_name='total_stake')),
                ('free_stake', models.BigIntegerField(default=0, help_text='free_stake', verbose_name='free_stake')),
            ],
            options={
                'verbose_name': '机器列表',
                'db_table': 'pool',
            },
        ),
        migrations.AddField(
            model_name='mechine',
            name='pid',
            field=models.BigIntegerField(default=0, help_text='pid', verbose_name='pid'),
        ),
    ]
