# Generated by Django 4.0.4 on 2022-05-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0010_pool_mechine_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='owner',
            field=models.CharField(default='', help_text='拥有者', max_length=100, verbose_name='拥有者'),
        ),
    ]
