# Generated by Django 4.0.4 on 2022-05-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0011_alter_pool_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='update_time',
            field=models.CharField(default='', help_text='更新时间', max_length=100, verbose_name='更新时间'),
        ),
    ]
