# Generated by Django 4.0.4 on 2022-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0012_pool_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechine',
            name='start_time',
            field=models.BigIntegerField(default=0, help_text='当前状态', verbose_name='当前状态'),
        ),
    ]
