# Generated by Django 4.0.4 on 2022-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0013_mechine_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechine',
            name='start_time',
            field=models.BigIntegerField(default=0, help_text='开始挖矿时间', verbose_name='开始挖矿时间'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='status_now',
            field=models.CharField(default='', help_text='当前状态', max_length=100, unique=True, verbose_name='当前状态'),
        ),
    ]
