# Generated by Django 4.0.4 on 2022-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0015_alter_mechine_status_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymachincount',
            name='data',
            field=models.FloatField(default=0, help_text='data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='dailymeachine',
            name='amount',
            field=models.FloatField(default=0, help_text='amount', verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='dailystakeamount',
            name='data',
            field=models.FloatField(default=0, help_text='data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='dailyusercount',
            name='data',
            field=models.FloatField(default=0, help_text='data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='history_amount',
            field=models.FloatField(default=0, help_text='历史总产量', verbose_name='历史总产量'),
        ),
        migrations.AlterField(
            model_name='mechine',
            name='stake_amount',
            field=models.FloatField(default=0, help_text='质押金额', verbose_name='质押金额'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='cap',
            field=models.FloatField(default=0, help_text='池子容量', verbose_name='池子容量'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='commission',
            field=models.FloatField(default=0, help_text='佣金', verbose_name='佣金'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='free_stake',
            field=models.FloatField(default=0, help_text='free_stake', verbose_name='free_stake'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='total_stake',
            field=models.FloatField(default=0, help_text='total_stake', verbose_name='total_stake'),
        ),
        migrations.AlterField(
            model_name='staker',
            name='availableRewards',
            field=models.FloatField(default=0, help_text='availableRewards', verbose_name='availableRewards'),
        ),
        migrations.AlterField(
            model_name='staker',
            name='locked',
            field=models.FloatField(default=0, help_text='locked', verbose_name='locked'),
        ),
        migrations.AlterField(
            model_name='staker',
            name='rewardDebt',
            field=models.FloatField(default=0, help_text='rewardDebt', verbose_name='rewardDebt'),
        ),
    ]
