# Generated by Django 4.0.4 on 2022-05-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0016_alter_dailymachincount_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystakeamount',
            name='data',
        ),
        migrations.AddField(
            model_name='dailystakeamount',
            name='all_amount',
            field=models.FloatField(default=0, help_text='all_amount', verbose_name='all_amount'),
        ),
        migrations.AddField(
            model_name='dailystakeamount',
            name='used_amount',
            field=models.FloatField(default=0, help_text='used_amount', verbose_name='used_amount'),
        ),
    ]
