# Generated by Django 4.0.4 on 2022-05-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0017_remove_dailystakeamount_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeachine',
            name='pubkey',
            field=models.CharField(default='', help_text='矿机公钥', max_length=100, verbose_name='矿机公钥'),
        ),
    ]
